name: AM-R
favicon: null
layout_spectrum: 0.6168133672326803
typography_spectrum: 0.047596839256584644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8235885510221124
  lightness: 0.2518897589761764
  saturation: 0.7749659363180399
  rhythmicContrast: 0.9760524933226407
purpose: []
